name: curl-gen
version: 0.6.0
github: PKopel/curl-gen
license: BSD3
author: Paweł Kopel
maintainer: Pawel.Kopel2@gmail.com
copyright: 2022 Paweł Kopel

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/PKopel/curl-gen#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - attoparsec
  - aeson == 1.5.6.0
  - interpolatedstring-perl6
  - unix

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  curl-gen:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - curl-gen
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  curl-gen-server:
    main: Main.hs
    source-dirs: server
    dependencies:
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  curl-gen-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - rio >= 0.1.12.0
      - curl-gen
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
